#################################
## Build development container ##
#################################
FROM php:8.3-fpm-alpine3.20

LABEL maintainer="Nizar El Berjawi <nizarberjawi12@gmail.com>"

ARG USER
ARG GID
ARG UID

WORKDIR /var/www/html/

RUN echo "UTC" > /etc/timezone
RUN apk upgrade --no-cache && \
  apk add --no-cache --virtual .persistent-deps \
    git \
    npm \
    zip \
    curl \
    unzip \
    nodejs \
    libzip-dev \
    postgresql-dev \
  && apk add --no-cache --virtual .build-deps \
    $PHPIZE_DEPS \
  && pecl install \
    redis \
  && docker-php-ext-install \
    pdo \
    pgsql \
    pdo_pgsql \
    zip \
  && docker-php-ext-enable \
    redis

RUN addgroup --gid ${GID} ${USER}
RUN adduser \
  --ingroup ${USER} \ 
  --gecos ${USER} \
  --uid ${UID} \
  --shell /bin/sh \
  --disabled-password ${USER}

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

EXPOSE 9000

CMD ["php-fpm"]

USER ${USER}